// frontend-bk/src/helpdesk/components/Settings/Assignment Rules/AssignmentRulesSection.vue
<template>
  <CFConditions
    v-if="props.conditions.length > 0"
    :conditions="props.conditions"
    :level="0"
    :disableAddCondition="props.errors !== ''"
  />
  <div
    v-if="props.conditions.length == 0"
    class="flex p-4 items-center cursor-pointer justify-center gap-2 text-sm border border-outline-gray-2 text-ink-gray-5 rounded-5"
    @click="
      props.conditions.push(['', '', '']);
      validateAssignmentRule(props.name);
    "
  >
    <LucidePlus class="size-4" />
    {{ __("Add a condition") }}
  </div>
  <div class="flex items-center justify-between mt-2">
    <Dropdown
      v-if="props.conditions.length > 0"
      class="mt-2"
      v-slot="{ open }"
      :options="dropdownOptions"
    >
      <Button
        :disabled="props.errors !== ''"
        :icon-right="open ? 'lucide-chevron-up' : 'lucide-chevron-down'"
        :label="__('Add condition')"
      />
    </Dropdown>
    <ErrorMessage
      v-if="props.conditions.length > 0"
      :message="props.errors"
      class="mt-2"
    />
  </div>
</template>

<script setup lang="ts">
import LucidePlus from "~icons/lucide/plus";
import CFConditions from "@/helpdesk/components/conditions-filter/CFConditions.vue";
import { validateConditions } from "@/helpdesk/utils";
import { watchDebounced } from "@vueuse/core";
import { Button, Dropdown, ErrorMessage } from "frappe-ui";
import { validateAssignmentRule } from "@/helpdesk/stores/assignmentRules";
import { __ } from "@/helpdesk/translation";

const props = defineProps({
  conditions: Array<any>,
  name: String,
  errors: String,
});

const getConjunction = () => {
  let conjunction = "and";
  props.conditions.forEach((condition) => {
    if (typeof condition == "string") {
      conjunction = condition;
    }
  });
  return conjunction;
};

const dropdownOptions = [
  {
    label: __("Add condition"),
    onClick: () => {
      addCondition();
    },
  },
  {
    label: __("Add condition group"),
    onClick: () => {
      const conjunction = getConjunction();
      props.conditions.push(conjunction, [[]]);
    },
  },
];

const addCondition = () => {
  const isValid = validateConditions(props.conditions);

  if (!isValid) {
    return;
  }
  const conjunction = getConjunction();

  props.conditions.push(conjunction, ["", "", ""]);
};

watchDebounced(
  () => [...props.conditions],
  () => {
    validateAssignmentRule(props.name);
  },
  { deep: true, debounce: 300 }
);
</script>

// frontend/src/modules/crm/components/Settings/AssignmentRulesSection.tsx
import { useEffect, useRef } from 'react'
import { __ } from '@/core/i18n'
import { Button, Dropdown, ErrorMessage } from '@/design-system'
import { CFConditions } from '@/shared/components/ConditionsFilter'
import type { ConditionList } from '@/shared/types/conditions'
import { validateConditions } from '@/shared/utils/conditions'

export interface AssignmentRulesSectionProps {
  conditions: ConditionList
  errors: string
  doctype: string
  onChange: (conditions: ConditionList) => void
  onValidate: () => void
  emptyLabel?: string
  debounce?: number
}

function getConjunction(conditions: ConditionList): string {
  let conjunction = 'and'
  conditions.forEach((condition) => {
    if (typeof condition === 'string') conjunction = condition
  })
  return conjunction
}

export function AssignmentRulesSection({
  conditions,
  errors,
  doctype,
  onChange,
  onValidate,
  emptyLabel,
  debounce = 300,
}: AssignmentRulesSectionProps) {
  const validate = useRef(onValidate)
  useEffect(() => {
    validate.current = onValidate
  })

  useEffect(() => {
    const timer = setTimeout(() => validate.current(), debounce)
    return () => clearTimeout(timer)
  }, [conditions, debounce])

  function addCondition() {
    if (!validateConditions(conditions)) return
    onChange([...conditions, getConjunction(conditions), ['', '', '']])
  }

  return (
    <>
      {conditions.length > 0 && (
        <CFConditions
          conditions={conditions}
          onChange={onChange}
          level={0}
          disableAddCondition={errors !== ''}
          doctype={doctype}
        />
      )}
      {conditions.length === 0 && (
        <div
          className="flex cursor-pointer items-center justify-center gap-2 rounded-md border border-outline-gray-2 p-4 text-sm text-ink-gray-5"
          onClick={() => onChange([['', '', '']])}
        >
          <span className="lucide-plus h-4" aria-hidden="true" />
          {emptyLabel ?? __('Add a Condition')}
        </div>
      )}
      <div className="mt-2 flex items-center justify-between">
        {conditions.length > 0 && (
          <div>
            <Dropdown
              options={[
                { label: __('Add Condition'), onClick: addCondition },
                {
                  label: __('Add Condition Group'),
                  onClick: () => onChange([...conditions, getConjunction(conditions), [[]]]),
                },
              ]}
            >
              {({ open }) => (
                <Button
                  disabled={errors !== ''}
                  iconRight={open ? 'lucide-chevron-up' : 'lucide-chevron-down'}
                  label={__('Add Condition')}
                />
              )}
            </Dropdown>
          </div>
        )}
        {conditions.length > 0 && <ErrorMessage message={errors} />}
      </div>
    </>
  )
}
